/**
 * formatter.ts — Output formatting for review results.
 *
 * Converts the structured ReviewResult into human-readable output:
 *  1. formatReviewAsMarkdown() — GitHub-flavored markdown for PR comments,
 *     with findings grouped by severity in tables.
 *  2. formatReviewForConsole() — ANSI-colored terminal output with
 *     red/yellow/cyan severity indicators. Detects TTY and falls back
 *     to plain text when piped.
 */

import { ReviewResult, ReviewFinding, Severity } from "./types";

// --- Markdown formatting (for GitHub PR comment) ---

export function formatReviewAsMarkdown(review: ReviewResult): string {
  const assessmentIcon =
    review.overall_assessment === "approve"
      ? ":white_check_mark:"
      : review.overall_assessment === "request_changes"
        ? ":warning:"
        : ":speech_balloon:";

  const assessmentLabel =
    review.overall_assessment === "approve"
      ? "Approve"
      : review.overall_assessment === "request_changes"
        ? "Request Changes"
        : "Comment";

  const lines: string[] = [
    `## :mag: AI Code Review`,
    "",
    `**Overall Assessment**: ${assessmentIcon} ${assessmentLabel}`,
    "",
    `### Summary`,
    review.summary,
    "",
  ];

  const critical = review.findings.filter((f) => f.severity === "critical");
  const warnings = review.findings.filter((f) => f.severity === "warning");
  const info = review.findings.filter((f) => f.severity === "info");

  if (review.findings.length === 0) {
    lines.push("### Findings", "", "No issues found. The code looks good!", "");
  } else {
    lines.push("### Findings", "");

    if (critical.length > 0) {
      lines.push(`#### :red_circle: Critical (${critical.length})`, "");
      critical.forEach((f) => lines.push(formatFindingMarkdown(f)));
      lines.push("");
    }

    if (warnings.length > 0) {
      lines.push(`#### :orange_circle: Warnings (${warnings.length})`, "");
      warnings.forEach((f) => lines.push(formatFindingMarkdown(f)));
      lines.push("");
    }

    if (info.length > 0) {
      lines.push(`#### :blue_circle: Info (${info.length})`, "");
      info.forEach((f) => lines.push(formatFindingMarkdown(f)));
      lines.push("");
    }
  }

  lines.push(
    "### Files Reviewed",
    "",
    ...review.files_reviewed.map((f) => `- \`${f}\``),
    "",
    "---",
    "*Review generated by AI Code Review Agent*"
  );

  return lines.join("\n");
}

function formatFindingMarkdown(finding: ReviewFinding): string {
  const location = finding.line_number
    ? `\`${finding.file}:${finding.line_number}\``
    : `\`${finding.file}\``;

  return [
    `- **${finding.title}** (${finding.category}) — ${location}`,
    `  ${finding.description}`,
    `  > **Suggestion**: ${finding.suggestion}`,
    "",
  ].join("\n");
}

// --- Console formatting (ANSI colors) ---

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const RED = "\x1b[31m";
const YELLOW = "\x1b[33m";
const CYAN = "\x1b[36m";
const GREEN = "\x1b[32m";
const DIM = "\x1b[2m";

function severityColor(severity: Severity): string {
  switch (severity) {
    case "critical":
      return RED;
    case "warning":
      return YELLOW;
    case "info":
      return CYAN;
  }
}

function severityLabel(severity: Severity): string {
  switch (severity) {
    case "critical":
      return "CRITICAL";
    case "warning":
      return "WARNING";
    case "info":
      return "INFO";
  }
}

export function formatReviewForConsole(review: ReviewResult): string {
  const useColor = process.stdout.isTTY ?? false;

  const c = (color: string, text: string) =>
    useColor ? `${color}${text}${RESET}` : text;

  const lines: string[] = [
    c(BOLD, "=== AI Code Review ==="),
    "",
    `Overall: ${c(
      review.overall_assessment === "approve"
        ? GREEN
        : review.overall_assessment === "request_changes"
          ? RED
          : YELLOW,
      review.overall_assessment.toUpperCase()
    )}`,
    "",
    c(BOLD, "Summary:"),
    review.summary,
    "",
  ];

  if (review.findings.length === 0) {
    lines.push(c(GREEN, "No issues found."), "");
  } else {
    lines.push(c(BOLD, `Findings (${review.findings.length}):`), "");

    for (const finding of review.findings) {
      const color = severityColor(finding.severity);
      const label = severityLabel(finding.severity);
      const location = finding.line_number
        ? `${finding.file}:${finding.line_number}`
        : finding.file;

      lines.push(
        `  ${c(color, `[${label}]`)} ${c(BOLD, finding.title)}`,
        `  ${c(DIM, location)} (${finding.category})`,
        `  ${finding.description}`,
        `  ${c(CYAN, "Suggestion:")} ${finding.suggestion}`,
        ""
      );
    }
  }

  lines.push(
    c(DIM, `Files reviewed: ${review.files_reviewed.join(", ")}`)
  );

  return lines.join("\n");
}
